@api = http://localhost:5000/api
@json = Content-Type: application/json
@auth = Authorization: Bearer {{login.response.body.access_token}}

###
POST {{api}}/resource/devimport
{{json}}

{
    "Clients": [
        {
            "Id": "dev-client",
            "Secret": "dev-secret",
            "GrantType": "client_credentials",
            "Scopes": "openid profile identity-api identity-api-privileged",
            "RedirectUrl": "http://localhost:5000"
        }
    ]
}

###
# @name login
POST http://localhost:5000/connect/token
Content-Type: application/x-www-form-urlencoded

grant_type=client_credentials
&client_id=dev-client
&client_secret=dev-secret

###
GET {{api}}/accounts
{{auth}}

###
POST {{api}}/account/spam
{{auth}}
{{json}}

{
    "to": [
        "9fd3c38e-58b0-4af1-80d1-1895af91f1f9",
        "3269cb19-1d39-40d3-a55e-e3e9779b6e0b",
        "ac4d3e32-c2d6-4f99-9aef-0fcd62a568a6"
    ],
    "subject": "cmu-sei",
    "body": "Dear {name}, this is an email body.  don't squander it."
}
